CREATE SEQUENCE seq_reserva
START WITH 1
INCREMENT BY 1;

CREATE TABLE T_FIN_RESERVAS (
    ID_RESERVA INTEGER NOT NULL PRIMARY KEY,
    NOME_RESERVA VARCHAR2(100) NOT NULL,
    VALOR_TOTAL NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INICIO DATE NOT NULL,
    DATA_PRAZO DATE NOT NULL
);

CREATE SEQUENCE seq_receita
START WITH 1
INCREMENT BY 1;

CREATE TABLE T_FIN_RECEITAS (
    ID_RECEITA INTEGER NOT NULL PRIMARY KEY,
    NOME_RECEITA VARCHAR2(100) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INCLUSAO DATE NOT NULL
);

CREATE SEQUENCE seq_despesa
START WITH 1
INCREMENT BY 1;

CREATE TABLE T_FIN_DESPESAS (
    ID_DESPESA INTEGER NOT NULL PRIMARY KEY,
    NOME_DESPESA VARCHAR2(100) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INCLUSAO DATE NOT NULL
);
