CREATE TABLE T_FIN_USER (
    ID_USUARIO INTEGER PRIMARY KEY,
    NOME_COMPLETO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    IDADE_NASC DATE NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    SENHA VARCHAR2(50) NOT NULL
);

CREATE TABLE T_FIN_CATEGORIAS (
    ID_CATEGORIA INTEGER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);

CREATE TABLE T_FIN_RESERVAS (
    ID_RESERVA INTEGER PRIMARY KEY,
    NOME_RESERVA VARCHAR2(100) NOT NULL,
    VALOR_TOTAL NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INICIO DATE NOT NULL,
    DATA_PRAZO DATE NOT NULL,
    T_FIN_USER_ID_USUARIO INTEGER NOT NULL,
    CONSTRAINT T_FIN_RESERVAS_T_FIN_USER_FK
        FOREIGN KEY (T_FIN_USER_ID_USUARIO)
        REFERENCES T_FIN_USER(ID_USUARIO)
);

CREATE TABLE T_FIN_INVESTIMENTOS (
    ID_INVESTIMENTO INTEGER PRIMARY KEY,
    NOME_INVESTIMENTO VARCHAR2(100) NOT NULL,
    VALOR_TOTAL NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INCLUSAO DATE NOT NULL,
    NOME_INSTITUICAO VARCHAR2(100),
    T_FIN_USER_ID_USUARIO INTEGER NOT NULL,
    CONSTRAINT T_FIN_INVESTIMENTOS_T_FIN_USER_FK
        FOREIGN KEY (T_FIN_USER_ID_USUARIO)
        REFERENCES T_FIN_USER(ID_USUARIO)
);

CREATE TABLE T_FIN_TRANSACAO (
    ID_TRANSACAO INTEGER PRIMARY KEY,
    TIPO VARCHAR2(50) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    T_FIN_RESERVAS_ID_RESERVA INTEGER,
    T_FIN_INVESTIMENTOS_ID_INVESTIMENTO INTEGER,
    CONSTRAINT T_FIN_TRANSACAO_T_FIN_RESERVAS_FK
        FOREIGN KEY (T_FIN_RESERVAS_ID_RESERVA)
        REFERENCES T_FIN_RESERVAS(ID_RESERVA),
    CONSTRAINT T_FIN_TRANSACAO_T_FIN_INVESTIMENTOS_FK
        FOREIGN KEY (T_FIN_INVESTIMENTOS_ID_INVESTIMENTO)
        REFERENCES T_FIN_INVESTIMENTOS(ID_INVESTIMENTO)
);

CREATE TABLE T_FIN_RECEITAS (
    ID_RECEITA INTEGER NOT NULL,
    NOME_RECEITA VARCHAR2(100) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INCLUSAO DATE NOT NULL,
    T_FIN_USER_ID_USUARIO INTEGER NOT NULL,
    T_FIN_CATEGORIAS_ID_CATEGORIA INTEGER NOT NULL,
    PRIMARY KEY (ID_RECEITA, T_FIN_USER_ID_USUARIO),
    CONSTRAINT T_FIN_RECEITAS_T_FIN_USER_FK
        FOREIGN KEY (T_FIN_USER_ID_USUARIO)
        REFERENCES T_FIN_USER(ID_USUARIO),
    CONSTRAINT T_FIN_RECEITAS_T_FIN_CATEGORIAS_FK
        FOREIGN KEY (T_FIN_CATEGORIAS_ID_CATEGORIA)
        REFERENCES T_FIN_CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE T_FIN_DESPESAS (
    ID_DESPESA INTEGER NOT NULL,
    NOME_DESPESA VARCHAR2(100) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INCLUSAO DATE NOT NULL,
    T_FIN_USER_ID_USUARIO INTEGER NOT NULL,
    T_FIN_CATEGORIAS_ID_CATEGORIA INTEGER NOT NULL,
    PRIMARY KEY (ID_DESPESA, T_FIN_USER_ID_USUARIO),
    CONSTRAINT T_FIN_DESPESAS_T_FIN_USER_FK
        FOREIGN KEY (T_FIN_USER_ID_USUARIO)
        REFERENCES T_FIN_USER(ID_USUARIO),
    CONSTRAINT T_FIN_DESPESAS_T_FIN_CATEGORIAS_FK
        FOREIGN KEY (T_FIN_CATEGORIAS_ID_CATEGORIA)
        REFERENCES T_FIN_CATEGORIAS(ID_CATEGORIA)
);
